# Generated by Django 4.2.13 on 2024-05-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0004_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
