# Generated by Django 4.2.13 on 2024-06-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0006_alter_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='Languages',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
